apps/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_home_page, name='home'),
    path('categories/<int:category_id>/', views.show_category_articles_page, name='category-articles'),
    path('posts/<int:post_id>/', views.show_post_page, name='post-detail'),
    path('posts/<int:post_id>/update/', views.UpdatePost.as_view(), name='post-update'),
    path('posts/<int:post_id>/delete/', views.DeletePost.as_view(), name='post-delete'),
    path('comments/<int:comment_id>/delete/', views.delete_post_comment, name='delete-comment'),
    path('contacts/', views.show_contacts_page, name='contacts'),
    path('create/', views.show_create_post_page, name='create-post'),
    path('faq/', views.show_faq_page, name='faq'),
    path('login/', views.show_login_page, name='login'),
    path('registration/', views.show_registration_page, name='registration'),
    path('logout/', views.user_logout, name='logout'),
    path('users/<str:username>/profile/', views.show_author_profile_page, name='profile'),
    path('posts/<int:post_id>/<str:action>/', views.add_like_or_dislike, name='add-vote'),
    path('search/', views.search, name='search')
]

# http://127.0.0.1:8000/ - запускается show_home_page
# http://127.0.0.1:8000/contacts
# http://127.0.0.1:8000/about
# http://127.0.0.1:8000/articles

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
from apps.blog_api import api_app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('', api_app.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

apps/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'  # название таблицы в единственном числе
        verbose_name_plural = 'Категории'  # название таблицы во множественном числе


"""Category
create table category(
    name varchar(100)
);

create table post(
category_id integer,
foreign key (category_id) references category(id)
);
"""


class Post(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    short_description = models.TextField(verbose_name='Краткое описание')
    full_description = models.TextField(verbose_name='Полное описание', null=True, blank=True)
    views_qty = models.IntegerField(default=0, verbose_name='Кол-во просмотров')
    preview = models.ImageField(upload_to='posts/previews/', verbose_name='Заставка', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', related_name='posts')

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'post_id': self.pk})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['id']


# создать таблицу FAQ
# question - charfield
# answer - textfield

# создать таблицу Comment
# text - textfield
# author - foreingkey
# created_at - datetimefield


class FAQ(models.Model):
    question = models.CharField(max_length=100)
    answer = models.TextField(max_length=100)

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Вопрос-ответ'
        verbose_name_plural = 'Вопросы-ответы'


class Comment(models.Model):
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class PostPhoto(models.Model):
    photo = models.ImageField(upload_to='posts/photos/', verbose_name='Фото')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост', related_name='photos')


class PostViewsCount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Like(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE, related_name='likes')
    user = models.ManyToManyField(User, related_name='likes')


class Dislike(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE, related_name='dislikes')
    user = models.ManyToManyField(User, related_name='dislikes')

apps/main/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['name', 'short_description', 'full_description', 'preview', 'category']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'short_description': forms.Textarea(attrs={'class': 'form-control'}),
            'full_description': forms.Textarea(attrs={'class': 'form-control'}),
            'preview': forms.FileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'password']


class RegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

apps/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Category, Post, Comment, Like, Dislike, PostViewsCount
from django.core.paginator import Paginator
from .forms import LoginForm, RegisterForm, CommentForm, PostForm
from django.contrib.auth import login, logout
from django.views.generic import UpdateView, DeleteView

# Create your views here.


class UpdatePost(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'main/create_post.html'
    pk_url_kwarg = 'post_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['page_title'] = 'Обновить пост'
        context['page_button'] = 'Обновить'
        return context


class DeletePost(DeleteView):
    model = Post
    template_name = 'main/post_confirm_delete.html'
    pk_url_kwarg = 'post_id'
    success_url = '/'

# posts/<int:post_id>/update/
def show_home_page(request):
    # select * from categories
    posts = Post.objects.all()
    for post in posts:
        try:
            post.likes
        except Exception as e:
            Like.objects.create(post=post)

        try:
            post.dislikes
        except Exception as e:
            Dislike.objects.create(post=post)

    paginator = Paginator(posts, 3)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {
        'posts': posts
    }
    return render(request, 'main/index.html', context)


def show_contacts_page(request):
    return render(request, 'main/contacts.html')


def show_faq_page(request):
    return render(request, 'main/faq.html')


def show_create_post_page(request):
    if not request.user.is_authenticated:
        return redirect('login')

    if request.method == 'POST':
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            # AnonymousUser
            form = form.save(commit=False)
            form.author = request.user
            form.save()
            return redirect('post-detail', form.id)
    else:
        form = PostForm()

    page_title = 'Создать пост'
    page_button = 'Создать'

    context = {
        'form': form,
        'page_title': page_title,
        'page_button': page_button
    }
    return render(request, 'main/create_post.html', context)

# переход на страницу faq frequently asked question


def show_registration_page(request):
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            form.save()  # отправляем данные в БД
            return redirect('login')
    else:
        form = RegisterForm()

    context = {
        'form': form
    }
    return render(request, 'main/registration.html', context)


def show_login_page(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()  # получаем пользователя с базы данных
            if user is not None:  # если пользователь найден, то заходим в его аккаунт
                login(request, user)
                return redirect('home')
    else:
        form = LoginForm()

    context = {
        'form': form
    }
    return render(request, 'main/login.html', context)


def show_category_articles_page(request, category_id):
    sort = request.GET.get('sort', 'id')

    posts = Post.objects.filter(category__id=category_id).order_by(sort)


    sorting_fields = {
        'По дате': ['created_at', '-created_at'],
        'По просмотрам': ['views_qty', '-views_qty'],
        'По названию': ['name', '-name']
    }
    context = {
        'posts': posts,
        'sorting_fields': sorting_fields
    }
    return render(request, 'main/category_articles.html', context)


def show_post_page(request, post_id):
    post = Post.objects.get(id=post_id)

    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.post = post
            form.save()
            return redirect('post-detail', post_id)
    else:
        form = CommentForm()

    comments = Comment.objects.filter(post=post)

    if request.user.is_authenticated:
        viewed_post, is_created = PostViewsCount.objects.get_or_create(
            post=post,
            user=request.user,
        )
        if is_created:
            post.views_qty += 1
            post.save()

    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'main/post_detail.html', context)

# отобразить на детальной странице все комментарии статьи

def user_logout(request):
    logout(request)
    return redirect('home')


def delete_post_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    post_id = comment.post.id
    comment.delete()
    return redirect('post-detail', post_id)


from django.contrib.auth.models import User


def show_author_profile_page(request, username):
    user = User.objects.get(username=username)

    posts = Post.objects.filter(author=user)

    total_comments = [post.comment_set.all().count() for post in posts]
    total_likes = [post.likes.user.all().count() for post in posts]
    total_dislikes = [post.dislikes.user.all().count() for post in posts]
    total_views = [post.views_qty for post in posts]

    context = {
        'user': user,
        'posts': posts,
        'total_comments': sum(total_comments),
        'total_likes': sum(total_likes),
        'total_dislikes': sum(total_dislikes),
        'total_views': sum(total_views)
    }
    return render(request, 'main/author_profile.html', context)


def add_like_or_dislike(request, post_id, action):
    post = Post.objects.get(id=post_id)

    if action == 'add_like':
        if request.user in post.likes.user.all():
            post.likes.user.remove(request.user.id)
        else:
            post.likes.user.add(request.user.id)
            post.dislikes.user.remove(request.user.id)
    elif action == 'add_dislike':
        if request.user in post.dislikes.user.all():
            post.dislikes.user.remove(request.user.id)
        else:
            post.dislikes.user.add(request.user.id)
            post.likes.user.remove(request.user.id)

    return redirect('post-detail', post_id)


def search(request):
    query = request.GET.get('q')

    if not query:
        posts = Post.objects.all()
    else:
        posts = Post.objects.filter(name__iregex=query)

    context = {
        'posts': posts
    }
    return render(request, 'main/search_page.html', context)

apps/main/templates/main/author_profile.html
{% extends 'base.html' %}

{% block title %}
    {{ user.username }}
{% endblock %}

{% block  content %}
	<ul class="list-group list-group-flush">
        <li class="list-group-item">
            <b>Имя пользователя: </b>{{ user.username }}
        </li>
        <li class="list-group-item">
            <b>Почта: </b>{{ user.email }}
        </li>
        <li class="list-group-item">
            <b>Дата регистрации: </b>{{ user.date_joined }}
        </li>
        <li class="list-group-item">
            <b>Кол-во просмотров: </b>{{ total_views }}
        </li>
        <li class="list-group-item">
            <b>Кол-во статей: </b>{{ posts.count }}
        </li>
        <li class="list-group-item">
            <b>Кол-во лайков: </b>{{ total_likes }}
        </li>
        <li class="list-group-item">
            <b>Кол-во дизлайков: </b>{{ total_dislikes }}
        </li>
        <li class="list-group-item">
            <b>Кол-во комментариев: </b>{{ total_comments }}
        </li>
    </ul>
    <div class="row row-gap-4 mb-4">
        {% for post in posts %}
            <div class="col-12 col-md-6 col-lg-4">{% include 'components/_card.html' %}</div>
        {% endfor %}
    </div>
{% endblock %}

apps/main/templates/main/category_articles.html
{% extends 'base.html' %}

{% block title %}
    Категория: {{ category.name }}
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between mb-4">
        <h2>Сортировка:</h2>
        <div class="d-flex column-gap-3">
            {% for key, value in sorting_fields.items %}
                {% if request.GET.sort == value.0 %}
                    <a href="?sort={{ value.1 }}">{{ key }}</a>
                {% else %}
                    <a href="?sort={{ value.0 }}">{{ key }}</a>
                {% endif %}
            {% endfor %}

        </div>
    </div>
    <div class="row row-gap-4 mb-4">
        {% for post in posts %}
            <div class="col-12 col-md-6 col-lg-4">{% include 'components/_card.html' %}</div>
        {% endfor %}
    </div>

    {% include 'components/_pagination.html' %}
{% endblock %}

apps/main/templates/main/contacts.html
{% extends 'base.html' %}

{% block title %}
    Страница контактов
{% endblock %}

apps/main/templates/main/create_post.html
{% extends 'base.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">{{ page_button }}</button>
    </form>
{% endblock %}

apps/main/templates/main/faq.html
{% extends 'base.html' %}

{% block title %}
	Страница FAQ
{% endblock %}

apps/main/templates/main/index.html
{% extends 'base.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    <div class="row row-gap-4 mb-4">
        {% for post in posts %}
            <div class="col-12 col-md-6 col-lg-4">{% include 'components/_card.html' %}</div>
        {% endfor %}
    </div>

    {% include 'components/_pagination.html' %}
{% endblock %}


{% comment %}получить все статьи из базы данных и добавить в переменную
переменную добавить в контекст
в index.html сделать циклы по переменной из контекста
{% endcomment %}

apps/main/templates/main/login.html
{% extends 'base.html' %}

{% block title %}
    Логин
{% endblock %}

{% block content %}
    <form class="my-5" method="post">
        {% csrf_token %}
        <h2 class="text-center">Вход в аккаунт</h2>

        {{ form.as_p }}

        <button class="btn btn-primary">Войти</button>
    </form>
{% endblock %}

apps/main/templates/main/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Удаление
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            Вы действительно хотите удалить статью с названием:
            <b>{{ post.name }}</b>
        </p>
        <input type="submit" value="Да" class="btn btn-danger">
        <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Нет</a>
    </form>

{% endblock %}

apps/main/templates/main/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.name }}
{% endblock %}


{% block extra_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.css"/>

    <style>


        .swiper {
            width: 100%;
            height: 100%;
        }

        .swiper-slide {
            text-align: center;
            font-size: 18px;
            background: #444;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .swiper-slide img {
            display: block;
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .swiper {
            width: 100%;
            height: 300px;
            margin-left: auto;
            margin-right: auto;
        }

        .swiper-slide {
            background-size: cover;
            background-position: center;
        }

        .mySwiper2 {
            height: 80%;
            width: 100%;
        }

        .mySwiper {
            height: 20%;
            box-sizing: border-box;
            padding: 10px 0;
        }

        .mySwiper .swiper-slide {
            width: 25%;
            height: 100%;
            opacity: 0.4;
        }

        .mySwiper .swiper-slide-thumb-active {
            opacity: 1;
        }

        .swiper-slide img {
            display: block;
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row mt-4">
        <div class="col-6">
            <div style="--swiper-navigation-color: #fff; --swiper-pagination-color: #fff" class="swiper mySwiper2">
                <div class="swiper-wrapper">
                    {% for post_photo in post.postphoto_set.all %}
                        <div class="swiper-slide">
                            <img src="{{ post_photo.photo.url }}"/>
                        </div>
                    {% endfor %}
                </div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>
            <div thumbsSlider="" class="swiper mySwiper">
                <div class="swiper-wrapper">
                    {% for post_photo in post.postphoto_set.all %}
                        <div class="swiper-slide">
                            <img src="{{ post_photo.photo.url }}"/>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-6">
            <h1 class="text-center">{{ post.name }}</h1>
            <ul class="list-group list-group-action mb-4">
                <li class="list-group-item list-group-item-action"><b>Автор: </b>{{ post.author }}</li>
                <li class="list-group-item list-group-item-action"><b>Категория: </b>{{ post.category }}</li>
                <li class="list-group-item list-group-item-action"><b>Кол-во просмотров: </b>{{ post.views_qty }}</li>
                <li class="list-group-item list-group-item-action"><b>Кол-во лайков: </b>{{ post.likes.user.all.count }}</li>
                <li class="list-group-item list-group-item-action"><b>Кол-во дизлайков: </b>{{ post.dislikes.user.all.count }}</li>
                <li class="list-group-item list-group-item-action"><b>Кол-во комментариев: </b>{{ post.comment_set.all.count }}</li>
                <li class="list-group-item list-group-item-action"><b>Дата публикации: </b>{{ post.created_at }}</li>
            </ul>

            <div class="d-flex column-gap-3">
                {% if request.user == post.author %}
                    <a href="{% url 'post-delete' post.id %}" class="btn btn-danger">Удалить</a>
                    <a href="{% url 'post-update' post.id %}" class="btn btn-secondary">Редактировать</a>
                {% endif %}

                {% if request.user.is_authenticated and request.user != post.author %}
                    <a href="{% url 'add-vote' post.id 'add_like' %}" class="btn btn-success">Лайк</a>
                    <a href="{% url 'add-vote' post.id 'add_dislike' %}" class="btn btn-danger">Дизлайк</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="my-4">
        <h2 class="text-center">Полное описание</h2>
        <p>{{ post.full_description }}</p>
    </div>
    <div class="mb-4">
        <div class="row row-gap-3 mb-4">
            {% for comment in comments %}
            <div class="col-6">{% include 'components/_comment-card.html' %}</div>
            {% endfor %}

        </div>

        {% if request.user.is_authenticated %}
            <form class="form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark">Отправить</button>
            </form>
        {% else %}
            <p>
                Только авторизованные пользователи могут оставлять комментарий...
                <a href="{% url 'login' %}">Войти</a>
            </p>
        {% endif %}

    </div>
{% endblock %}


{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.js"></script>
    <script>
        var swiper = new Swiper(".mySwiper", {
            spaceBetween: 10,
            slidesPerView: 4,
            freeMode: true,
            watchSlidesProgress: true,
        });
        var swiper2 = new Swiper(".mySwiper2", {
            spaceBetween: 10,
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
            thumbs: {
                swiper: swiper,
            },
        });
    </script>
{% endblock %}

apps/main/templates/main/registration.html
{% extends 'base.html' %}

{% block title %}
	Регистрация
{% endblock %}

{% block content %}
    <form class="my-5" method="post">  {% comment %}get{% endcomment %}
        {% csrf_token %}
        <h2 class="text-center">Создание аккаунта</h2>

        {{ form.as_p }}

        <button class="btn btn-primary">Создать</button>
    </form>
{% endblock %}

apps/main/templates/main/search_page.html
{% extends 'base.html' %}

{% block title %}
    Результаты поиска
{% endblock %}


{% block content %}
    <div class="row flex-column align-items-center row-gap-3">
    {% for post in posts %}
        <div class="col-6">
            <div class="card">
              <div class="card-header">
                {{ post.created_at }}
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ post.name }}</h5>
                <p class="card-text">{{ post.short_description }}</p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Подробнее</a>
              </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}